config/routes.rb
Rails.application.routes.draw do
  get 'top_target/toptarget'
  get 'trends/trends'
  get 'top_doctor/topdoctor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "articles#index"
  get "/articles", to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/top_doctor_controller.rb
class TopDoctorController < ApplicationController
  def topdoctor
  end
end

app/controllers/top_target_controller.rb
class TopTargetController < ApplicationController
  def toptarget
  end
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  def trends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/top_doctor_helper.rb
module TopDoctorHelper
end

app/helpers/top_target_helper.rb
module TopTargetHelper
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/articles/index.html.erb
<div class="vizparagraph"><p>The purpose of this web application is to display various perscription KPIs so doctors can identify trends in products. To view each dashboard navigate with the above buttons.</br></p></div>
<%= link_to "https://hack.osu.edu/2021/" do %>
	<%= image_tag "hack-logo.svg", class:"logo2" %>
<% end %>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails2HOT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header>
	  	<div class="title">
			<h1>Veeva Systems Doctor Perscription KPIs</h1>
		</div>
		</br>
		<div class="holder">
			<%= link_to "Home", articles_path, class:"button"%>
			<%= link_to "Top Doctors", top_doctor_topdoctor_path, class:"button"%>
			<%= link_to "Trends", trends_trends_path, class:"button"%>
			<%= link_to "Top Targets", top_target_toptarget_path, class:"button"%>
		</div>
	</header>
	<article>
	  	<div class="lines">
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
	  	</div>
	 	
		<%= yield %>
    <article>
    <footer class="footer">
    	<div class="flex-container">
			<div class="flex-child magenta">
				</br>
				<h1>Created For: Hack Ohio 2021, Veeva Systems</h1>
				<h1>Created By: Andrew Connors, Alex Hass, Noah Hufnagel, Derek Nelson</h1>
				<h1>Credit To: Veeva Systems for the data source</h1>
		    </div>
		    <div class="flex-child green">
		    	<%= link_to "https://www.veeva.com/" do %>
   					<%= image_tag "veeva-v-shot_4x.png", class:"logo" %>
				<% end %>
		    </div>
		  
		</div>
    </footer>
  </body>
</html>

app/views/top_doctor/topdoctor.html.erb
<div class="vizheader"><h1>Top Doctors by Total Prescriptions</h1></div>
<div class="vizparagraph"><p>This shows the top doctors for each product. The graph shows the total number of prescriptions (using TRx) written by the top 5 doctors by month. The tables show the top 5 doctors (by TRx) for each product over all months. There is also a product filter to focus the graph by product.</p></div>
<div class='tableauPlaceholder' id='viz1636248815827' style='position: relative'><noscript><a href='#'><img alt='Top Doctors per Product by TRx ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;TopDoctorsofEachProductbyTRx&#47;TopDoctorsperProductbyTRx&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='TopDoctorsofEachProductbyTRx&#47;TopDoctorsperProductbyTRx' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;TopDoctorsofEachProductbyTRx&#47;TopDoctorsperProductbyTRx&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1636248815827');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='1227px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
</br>

app/views/top_target/toptarget.html.erb
<div class="vizheader"><h1>Top And Bottom Doctors By Nrx Target Slopes</h1></div>
<div class="vizparagraph"><p>This shows the future projections of top and bottom doctors by NRx target slopes. The graphs show the slopes for the top and bottom 3 doctors over a six month time period. while the tables show the 5 doctors with the top and bottom  average slopes.</p></div>
<div class='tableauPlaceholder' id='viz1636249095687' style='position: relative'><noscript><a href='#'><img alt='Doctors by Slope ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Do&#47;DoctorsbySlope&#47;DoctorsbySlope&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='DoctorsbySlope&#47;DoctorsbySlope' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Do&#47;DoctorsbySlope&#47;DoctorsbySlope&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1636249095687');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='1327px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
</br>

app/views/trends/trends.html.erb
<div class="vizheader"><h1>Trends of Total Perscriptions on Product</h1></div>
<div class="vizparagraph"><p>This shows the trend of prescriptions based on product. The graphs show the trend of prescriptions by produced using NRx and using TRx. The tables reflect the same data as the graphs numerically.</p></div>
<div class='tableauPlaceholder' id='viz1636248744901' style='position: relative'><noscript><a href='#'><img alt='Trending Products ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Tr&#47;TrendingProducts&#47;TrendingProducts&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='TrendingProducts&#47;TrendingProducts' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Tr&#47;TrendingProducts&#47;TrendingProducts&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1636248744901');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='1277px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
</br>